
services:

  mariadb:
      container_name: mariadb-cont
      build: ./requirements/mariadb
      image: mariadb:alli
      volumes:
          - mariadb-data:/var/lib/mysql
      networks: 
        - inception_net
      restart: always
      env_file: 
        - ".env"

  # wordpress:
  #   container_name: wordpress-cont
  #   image: wordpress:alli
  #   build: ./requirements/wordpress
  #   volumes: 
  #     - wordpress-data:/var/www/html
  #   depends_on:
  #     - mariadb
  #   env_file:
  #     - .env
  #   networks: 
  #     - inception_net
  #   restart: always

  # nginx:
  #   container_name: nginx-cont
  #   image: nginx:alli
  #   build: ./requirements/nginx
  #   ports:
  #     - "443:443" # for HHTPs
  #   volumes:
  #     - wordpress-data:/var/www/html
  #   depends_on:
  #     - wordpress
  #   env_file:
  #     - .env
  #   networks: 
  #     - inception_net
  #   restart: always

volumes:
  mariadb-data:
    name: mariadb-vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/alli/data/mariadb #setting a custom storage path

  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/alli/data/wordpress #setting a custom storage path


networks:
  inception_net:
    driver: bridge