
services:

  mariadb:
      container_name: mariadb-cont
      build: ./requirements/mariadb
      image: mariadb:alli
      volumes:
          - mariadb:/var/lib/mysql
      networks: 
          - inception_net
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: rootpasword
          MYSQL_DATABASE: mydatabase

  wordpress:
    container_name: wordpress-cont
    build: ./wordpress
    volumes: wordpress_files:/var/www/html
    networks:
      - inception_net
    depends_on:
      - mariadb

  nginx:
    container_name: nginx-cont
    build:
    context: ./nginx
    ports:
      - "443:443" # for HHTPs
    networks:
    - inception_net

volumes:
  mariadb-data:
    name: mariadb-vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/alli/data/mariadb #setting a custom storage path


networks:
  inception_net:
    driver: bridge